services:
  - type: web
    name: tourist-safety-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID_OTP
        sync: false
      - key: TWILIO_AUTH_TOKEN_OTP
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
      - key: TWILIO_ACCOUNT_SID_SOS
        sync: false
      - key: TWILIO_AUTH_TOKEN_SOS
        sync: false
      - key: PORT
        value: 10000
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
